-- MySQL Script generated by MySQL Workbench
-- Wed 03 Oct 2018 10:58:15 PM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Nomenclature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nomenclature` (
  `component_id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT(300) NULL,
  `quantity` INT UNSIGNED NOT NULL,
  `units` VARCHAR(20) NOT NULL,
  `for_sale` TINYINT(1) NOT NULL,
  `manufacture_date` DATETIME NULL,
  `expiration_date` DATETIME NULL,
  PRIMARY KEY (`component_id`),
  UNIQUE INDEX `component_id_UNIQUE` (`component_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `mydb`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route` (
  `route_id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`route_id`),
  UNIQUE INDEX `route_id_UNIQUE` (`route_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 30000;


-- -----------------------------------------------------
-- Table `mydb`.`Process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Process` (
  `process_id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `completion_time` TIME NOT NULL,
  PRIMARY KEY (`process_id`),
  UNIQUE INDEX `process_id_UNIQUE` (`process_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 40000;


-- -----------------------------------------------------
-- Table `mydb`.`Specification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Specification` (
  `specification_id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `component_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  `product_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  `route_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  `process_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`specification_id`),
  INDEX `fk_Specification_Nomenclature_idx` (`component_id` ASC),
  INDEX `fk_Specification_Nomenclature1_idx` (`product_id` ASC),
  UNIQUE INDEX `specification_id_UNIQUE` (`specification_id` ASC),
  INDEX `fk_Specification_Route1_idx` (`route_id` ASC),
  INDEX `fk_Specification_Process1_idx` (`process_id` ASC),
  CONSTRAINT `fk_Specification_Nomenclature`
    FOREIGN KEY (`component_id`)
    REFERENCES `mydb`.`Nomenclature` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specification_Nomenclature1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`Nomenclature` (`component_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specification_Route1`
    FOREIGN KEY (`route_id`)
    REFERENCES `mydb`.`Route` (`route_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Specification_Process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `mydb`.`Process` (`process_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20000;


-- -----------------------------------------------------
-- Table `mydb`.`Route_Process`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Route_Process` (
  `route_id` MEDIUMINT(5) NOT NULL,
  `process_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  `transportation_time` TIME NOT NULL,
  INDEX `fk_Route_Process_Process1_idx` (`process_id` ASC),
  INDEX `fk_Route_Process_Route1_idx` (`route_id` ASC),
  PRIMARY KEY (`route_id`, `process_id`),
  CONSTRAINT `fk_Route_Process_Process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `mydb`.`Process` (`process_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Route_Process_Route1`
    FOREIGN KEY (`route_id`)
    REFERENCES `mydb`.`Route` (`route_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workstation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Workstation` (
  `workstation_id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `description` TEXT(300) NULL,
  `process_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`workstation_id`),
  UNIQUE INDEX `workstation_id_UNIQUE` (`workstation_id` ASC),
  INDEX `fk_Workstation_Process1_idx` (`process_id` ASC),
  CONSTRAINT `fk_Workstation_Process1`
    FOREIGN KEY (`process_id`)
    REFERENCES `mydb`.`Process` (`process_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 50000;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `client_id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `current_client` TINYINT(1) NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 90000;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `order_id` MEDIUMINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `order_date` DATETIME NOT NULL,
  `client_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE INDEX `order_id_UNIQUE` (`order_id` ASC),
  INDEX `fk_Order_Client1_idx` (`client_id` ASC),
  CONSTRAINT `fk_Order_Client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`Client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 60000;


-- -----------------------------------------------------
-- Table `mydb`.`Product_Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product_Order` (
  `component_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  `order_id` MEDIUMINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`component_id`, `order_id`),
  INDEX `fk_Product_Order_Nomenclature1_idx` (`component_id` ASC),
  INDEX `fk_Product_Order_Order1_idx` (`order_id` ASC),
  CONSTRAINT `fk_Product_Order_Order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`Order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Product_Order_Nomenclature1`
    FOREIGN KEY (`component_id`)
    REFERENCES `mydb`.`Nomenclature` (`component_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
